global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
   monitor: 'docker-host-alpha'
scrape_configs:
  - job_name: 'prometheus'  
    static_configs:
    - targets: ['localhost:9090']         
  - job_name: 'node_exporter'
    static_configs:
    - targets: ['192.168.75.11:9100', '192.168.75.12:9100', '192.168.75.13:9100']

  - job_name: 'cadvisor'
    static_configs:
    - targets: ['192.168.75.11:8088']
  - job_name: 'cadvisor3'
    static_configs:
    - targets: ['192.168.75.13:8088']
  - job_name: 'cadvisor2'
    static_configs:
    - targets: ['192.168.75.12:8088']

rule_files:
  - "alert.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

