route:
    group_by: [Alertname]
    receiver: email-me

receivers:
    - name: email-me
      email_configs:
      - to: blabla@gmail.com
        from: blabla@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: "blabla@gmail.com"
        auth_identity: "blabla.gmail.com"
        auth_password: "VCC2020@"
